version: 3

tasks:
  tools:
    desc: Install tools
    cmds:
      - go install github.com/zabio3/godolint@latest
      - go install go.uber.org/mock/mockgen@latest
      - godolint --version
      - mockgen --version

  tidy:
    desc: Actualize dependencies
    cmds:
      - go mod tidy
      - task: vendor

  vendor:
    desc: Install dependencies
    cmds:
      - go mod vendor
      - go mod verify

  mock:
    desc: Generate mocks
    cmds:
      - mockgen --source internal/version/getter.go --destination internal/version/getter_mock_test.go --package version_test --typed

  lint:
    desc: Lint Dockerfile
    cmds:
      - golangci-lint --exclude-use-default=false run ./...

  buildpush:
    desc: Build container
    vars:
      TAGS:
        sh: go run cmd/main.go tags
    cmds:
      - go run cmd/main.go dockerfile
      - docker build {{ range .TAGS | splitLines }}-t alexeyco/devtools:{{ . }} {{ end }}.
      - docker push alexeyco/devtools --all-tags
