on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v5
        with:
          check-latest: true
      - run: go version
      - run: go install github.com/go-task/task/v3/cmd/task@latest
      - run: task buildpush
