on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true
      - run: go version
      - uses: golangci/golangci-lint-action@v3
      - run: go test -race ./...
